name: Publish Docker Image

on:
  push:
    tags:
      - '**'
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:

  call-publish-docker:
    uses: mdefenders/shared-workflows/.github/workflows/publish-docker.yaml@main
    with:
      build-args: | 
        "PYTHON_VERSION=${{ vars.PYTHON_VERSION }}"
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
